version: '3.9'

services:
  db:
    container_name: mariadb
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: mariadb
      MARIADB_PASSWORD: mariadb
      MARIADB_ROOT_PASSWORD: mariadb
      MARIADB_DATABASE: mariadb
    ports:
      - 3306:3306